### ISSUE TITLE
Spatch ask for pw

### ISSUE THREAD

**Issue by ghost** [OfficialKatana/SPatch#2]
@lianglixin  i open spatch  (not spromoter)
They ask for password what should i do?

![Screenshot_2021-07-03-14-55-43-85](https://user-images.githubusercontent.com/50813528/124347397-c8b6ad00-dc0e-11eb-9e06-9fd754b611c4.jpg)

**Comment by ghost** [comment]
See [SPatch official](http://spatch.die.lu) site for password

**Comment by ghost** [comment]
> See [SPatch official](http://spatch.die.lu) site for password

Your website is unreachable even with vpn 

EDIT:
Checked using everyone down or just me website is that right yes your website down @lianglixin

**Comment by Almgirjhanzaib** [comment]
@lianglixin  I open the site, it says put zero four-time and long-press D, but unable to unlock. Please can you help me

**Comment by ghost** [comment]
> @lianglixin I open the site, it says put zero four-time and long-press D, but unable to unlock. Please can you help me

🗿🗿🗿🗿🗿🗿🗿🗿
